### PR TITLE
DW-6076 Replace AmazonEC2RoleforSSM with AmazonSSMManagedInstanceCore

### PR DESCRIPTION
**Pull request by jjdmw**

### CODE REVIEW

**Review by jjdmw — COMMENTED** [review]
Both of these files include a separate attachment for CloudWatchAgentServerPolicy so the reduced scope of the new role shouldn't be a problem here. Ready for review.

**Comment by jjdmw** [comment]
the pull request terraform check appears to have failed due to some recent security changes rather than as a result of this change - will discuss.

**Review by ChrisScottThomas — DISMISSED** [review]
LGTM

**Review by steveburton4 — APPROVED** [review]

**Comment by ChrisScottThomas** [comment]
Bundled this into another PR.

**Pull request closed without merging**
